[versions]
cucumber="7.14.0"
gitSemVer = "3.1.7"
dokka = "1.9.20"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin", version.ref = "gitSemVer" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.67.2" }
taskTree = { id = "com.dorongold.task-tree", version = "4.0.0" }

[libraries]
mockito-kotlin = {group = "org.mockito.kotlin", name = "mockito-kotlin", version = "5.4.0" }
cucumber-java = { group = "io.cucumber", name = "cucumber-java", version.ref = "cucumber" }
cucumber-junit = { group = "io.cucumber", name = "cucumber-junit", version.ref = "cucumber" }
cucumber-spring = { group = "io.cucumber", name = "cucumber-spring", version.ref = "cucumber" }
archunit = { group = "com.tngtech.archunit", name = "archunit", version = "1.3.0" }

[bundles]
cucmber-test = ["cucumber-java", "cucumber-junit"]